// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyjbsjcybhityldpkyxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5amJzamN5YmhpdHlsZHBreXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjEzOTQsImV4cCI6MjA3Mjg5NzM5NH0.E4b0syTTcA2gB8EBS6rq9dmqhVyZQqg1cv4MGTe_p3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});